# Generated by Django 5.1 on 2024-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='freemegabytes',
            new_name='freegigabytes',
        ),
        migrations.AlterField(
            model_name='dataanalytic',
            name='freebytesd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
